Repository Codeit-FE08-Part4-Team7/wedo, pull requests merged in 2024-10, with the labels that each got.

#6 Fix: eslint 규칙 수정
  .eslintrc.json
  .gitattributes
  .gitignore
  .husky/pre-commit
  .vscode/settings.json
  app/layout.tsx
  components.json
  package-lock.json
  package.json
Labels: 💻Env

#12 Fix: github issue template 위치 잘못된 것 수정
  .github/ISSUE_TEMPLATE/bug_issue.md
  .github/ISSUE_TEMPLATE/discussion_issue.md
  .github/ISSUE_TEMPLATE/todo_issue.md
Labels: 🩹Fix

#14 Fix: 기존의 잘못된 경로의 이슈템플릿 폴더 제거
  .github/workflows/ISSUE_TEMPLATE/bug_issue.md
  .github/workflows/ISSUE_TEMPLATE/discussion_issue.md
  .github/workflows/ISSUE_TEMPLATE/todo_issue.md
Labels: 🩹Fix

#23 Feat: Tailwind config 수정
  app/page.tsx
  tailwind.config.ts
Labels: ✨Feat, 💻Env, 🎨Design

#26 Feat: NextAuth를 사용한 일반 로그인 로직 구현
  .vscode/settings.json
  apis/auth.ts
  apis/fetchExtended.ts
  apis/fetchExtendedClient.ts
  apis/git_tracking_file
  app/api/auth/[...nextauth]/route.ts
  app/layout.tsx
  app/login/client/page.tsx
  app/login/page.tsx
  app/login/server/page.tsx
  app/signup/page.tsx
  auth.config.ts
  auth.ts
  dtos/AuthDtos.ts
  middleware.ts
  package-lock.json
  package.json
  routes.ts
  tsconfig.json
  types/next-auth.d.ts
Labels: ✨Feat, 📦Chore

#32 Feat: 공통 모달 컴포넌트 구현
  components/@common/modal/Dialog.tsx
  components/@common/modal/Modal.tsx
  components/@common/modal/Sheet.tsx
  components/git_tracking_file
  package-lock.json
  package.json
Labels: ✨Feat, 📦Chore

#35 Feat: useToggle 커스텀 훅 구현
  hooks/useToggle.ts
Labels: ✨Feat

#38 Feat: 헤더 기능 추가
  .eslintrc.json
  .vscode/settings.json
  apis/fetchExtended.ts
  apis/fetchExtendedClient.ts
  apis/user.ts
  app/(pages)/[teamid]/page.tsx
  app/(pages)/layout.tsx
  app/(pages)/login/page.tsx
  app/(pages)/page.tsx
  app/(pages)/signup/page.tsx
  app/login/client/page.tsx
  app/login/server/page.tsx
  components/layout/AuthHeader.tsx
  components/layout/HeaderLayout.tsx
  components/layout/groups/GroupsResponsive.tsx
  components/layout/groups/NavigationMenuGroups.tsx
  components/layout/groups/SheetGroups.tsx
  components/ui/avatar.tsx
  components/ui/navigation-menu.tsx
  components/ui/sheet.tsx
  dtos/UserDtos.ts
  hooks/querys/user.ts
  next.config.mjs
  package-lock.json
  package.json
  public/images/git_tracking_file
  public/images/logo.png
  public/svg/burger.tsx
  public/svg/logo.svg
  public/svg/profile_fallback.svg
  tsconfig.json
Labels: ✨Feat, 💻Env, 📦Chore

#40 Feat: 공용 DropDown 컴포넌트를 제작한다
  components/@common/container/Container.tsx
  components/@common/dropdown/ActionsDropDown.tsx
  components/@common/dropdown/UserDropDown.tsx
  components/ui/dropdown.tsx
  package-lock.json
  package.json
Labels: ✨Feat, 📦Chore

#39 Feat: 공통 토스트 컴포넌트 구현
  app/layout.tsx
  components/@common/toast/Toast.tsx
  components/@common/toast/Toaster.tsx
  hooks/useToast.ts
  package-lock.json
  package.json
Labels: ✨Feat, 📦Chore

#41 Feat: 공용 컴포넌트 Input/Textarea, cva 인텔리센스, 페이지 파일, scrollbar style 추가
  .vscode/settings.json
  app/(pages)/(자유게시판)/addboard/page.tsx
  app/(pages)/(자유게시판)/board/[id]/page.tsx
  app/(pages)/(자유게시판)/boards/page.tsx
  app/(pages)/page.tsx
  components/@common/Input.tsx
  components/@common/Textarea.tsx
  styles/globals.css
Labels: ✨Feat

#48 Feat: 임시 파비콘 추가
  app/favicon.ico
Labels: ✨Feat, 🐛Bug

#51 Design: 모달 디자인 수정
  components/@common/modal/Dialog.tsx
  components/@common/modal/Sheet.tsx
Labels: 🎨Design

#56 Feat: Container 컴포넌트에 background props를 추가한다
  components/@common/container/Container.tsx
Labels: ✨Feat, ♻️Refactor

#53 Feat/Design: 공용 컴포넌트 Input/Textarea 1차 수정
  components/@common/Input.tsx
  components/@common/Textarea.tsx
  styles/globals.css
Labels: ✨Feat, 🎨Design

#60 Refactor: Container 컴포넌트에 백그라운드 클래스 명 지정 방식을 수정한다.
  app/(pages)/layout.tsx
  components/@common/container/Container.tsx
Labels: ♻️Refactor

#65 Chore: svgr import 타입 정의 파일 추가
  svgr.d.ts
  tsconfig.json
Labels: 📦Chore

#73 Fix: layout revalidate 적용 & Content-Type 문제 해결
  apis/fetchExtended.ts
  apis/image.ts
  app/(pages)/(team)/jointeam/page.tsx
  app/(pages)/[teamid]/page.tsx
  components/layout/HeaderLayout.tsx
  components/layout/groups/GroupsResponsive.tsx
  components/layout/groups/NavigationMenuGroups.tsx
  components/layout/groups/SheetGroups.tsx
  components/team/add_team/AddTeamForm.tsx
  lib/revalidate.ts
Labels: ✨Feat, 🩹Fix, 🐛Bug

#76 Fix/Refactor: 모달 버그 및 기능 수정 #66
  components/@common/modal/Modal.tsx
Labels: ✨Feat, ♻️Refactor, 🩹Fix, 🐛Bug

#77 Feat: 로그인 구현 완료
  .vscode/settings.json
  apis/action.ts
  apis/auth.ts
  app/(pages)/login/page.tsx
  components/@common/dropdown/NavigationMenu.tsx
  components/auth/InputField.tsx
  components/auth/login/LoginForm.tsx
  components/auth/login/OAuthLink.tsx
  components/layout/groups/NavigationMenuGroups.tsx
  components/ui/button.tsx
  components/ui/form.tsx
  components/ui/label.tsx
  components/ui/separator.tsx
  package-lock.json
  package.json
  public/images/google.png
  public/images/kakao.png
  public/images/visibility_off.png
  public/images/visibility_on.png
  tailwind.config.ts
Labels: ✨Feat, 🩹Fix, 🎨Design, 📦Chore

#91 Chore: dayjs 라이브러리를 설치한다
  package-lock.json
  package.json
Labels: 📦Chore

#92 Feat: 게시물 작성 페이지 구현
  apis/article.ts
  apis/articleComment.ts
  app/(pages)/(자유게시판)/addboard/page.tsx
  components/board/ImagePreviewInput.tsx
  next.config.mjs
  public/images/default_profile.png
  public/svg/comment.svg
  public/svg/like.svg
  public/svg/x.svg
  styles/globals.css
  tailwind.config.ts
Labels: ✨Feat, 🎨Design, 💄Style, 📦Chore

#93 Feat: 계정 설정 페이지 구현
  .vscode/settings.json
  apis/action.ts
  apis/fetchExtended.ts
  apis/user.ts
  app/(pages)/mypage/page.tsx
  app/api/auth/callback/google/route.ts
  app/api/auth/callback/kakao/route.ts
  app/api/user/route.ts
  components/@common/ImageInput.tsx
  components/@common/Input.tsx
  components/@common/toast/Toast.tsx
  components/auth/InputField.tsx
  components/auth/mypage/PasswordEditForm.tsx
  components/auth/mypage/ProfileEditInput.tsx
  components/auth/mypage/SecessionModal.tsx
  components/layout/AuthHeader.tsx
  components/layout/HeaderLayout.tsx
  dtos/UserDtos.ts
  lib/cookie.ts
  next.config.mjs
  public/images/alert_danger.png
  public/images/pencil.png
  public/images/profile_pfp_register.png
  public/images/secession.png
  public/images/x.png
Labels: ✨Feat, 🎨Design, 📦Chore

#97 Feat: 자유게시판, 게시물 상세 페이지 임시 구현
  app/(pages)/(자유게시판)/board/[id]/page.tsx
  app/(pages)/(자유게시판)/boards/page.tsx
Labels: ✨Feat

#109 Fix: OAUTH_PARAMS export 제거
  app/(pages)/login/page.tsx
Labels: 🩹Fix, 🐛Bug

#112 Fix: refreshToken 에러수정 (테스트는 완벽하게 해보지 못함)
  apis/auth.ts
  apis/fetchExtended.ts
  app/api/auth/refresh-token/route.ts
  middleware.ts
Labels: 🐛Bug

#113 Chore: dev 및 main 브랜치 빌드 자동화 액션 추가
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-main.yml
  build.sh
Labels: 📦Chore

#116 Fix: routes.ts 파일 업로드
  routes.ts
Labels: 🩹Fix

#117 Chore: react-intersection-observer 라이브러리 추가
  package-lock.json
  package.json
  public/svg/badge.svg
  public/svg/kebab.svg
  public/svg/search.svg
  styles/globals.css
Labels: 🎨Design, 📦Chore

#121 Fix: 할 일 목록 link 추가
  components/team/with_team/TeamTaskListCard.tsx
Labels: ✨Feat, 🩹Fix

#124 Chore: react-visually-hidden 설치
  package-lock.json
  package.json
Labels: 📦Chore

#125 Feat: 할 일 상세 페이지를 구현한다.
  apis/task.ts
  app/(pages)/(team)/[teamid]/tasks/[tasklistid]/@taskdetail/(.)task/[taskid]/page.tsx
  app/(pages)/(team)/[teamid]/tasks/[tasklistid]/@taskdetail/default.tsx
  app/(pages)/(team)/[teamid]/tasks/[tasklistid]/layout.tsx
  app/(pages)/(team)/[teamid]/tasks/[tasklistid]/page.tsx
  app/(pages)/(team)/[teamid]/tasks/[tasklistid]/task/[taskid]/page.tsx
  app/(pages)/(team)/[teamid]/tasks/layout.tsx
  components/taskdetail/DeleteCommentModal.tsx
  components/taskdetail/DeleteTaskModal.tsx
  components/taskdetail/EditTaskModal.tsx
  components/taskdetail/TaskComment.tsx
  components/taskdetail/TaskCommentForm.tsx
  components/taskdetail/TaskCommentList.tsx
  components/taskdetail/TaskDetail.tsx
  components/taskdetail/TaskSheet.tsx
  components/tasks/taskList/TaskCard.tsx
  components/tasks/taskList/Tasks.tsx
  components/tasks/tasksMenu/TasksDate.tsx
  components/tasks/tasksMenu/TasksMenu.tsx
  components/ui/tasksheet.tsx
  constants/frequencyType.ts
  dtos/TaskDtos.ts
  public/images/check.png
  public/images/check_on.png
  public/images/checkbox_on.png
  public/images/default_userImage.png
  public/images/enter.png
  public/images/icon_time.png
  public/images/kebab.png
  queries/task.ts
  utils/convertDate.ts
Labels: ✨Feat, ♻️Refactor, 🎨Design, 📦Chore

#126 Fix: 팀 참여 페이지 로직 수정 #99
  app/(pages)/(team)/jointeam/page.tsx
  components/team/with_team/TeamInviteModalButton.tsx
Labels: 🩹Fix, 🐛Bug

#127 Feat: 마이히스토리 페이지를 구현 한다
  apis/user.ts
  app/(pages)/history/page.tsx
  components/tasks/taskList/DoneTask.tsx
  dtos/TaskDtos.ts
Labels: ✨Feat

#129 Feat: 게시판 쪽 페이지 구현
  apis/article.ts
  apis/articleComment.ts
  app/(pages)/(자유게시판)/addboard/page.tsx
  app/(pages)/(자유게시판)/board/[id]/PatchAndDelete.tsx
  app/(pages)/(자유게시판)/board/[id]/action.ts
  app/(pages)/(자유게시판)/board/[id]/page.tsx
  app/(pages)/(자유게시판)/boards/action.ts
  app/(pages)/(자유게시판)/boards/page.tsx
  app/(pages)/(자유게시판)/boards/section/Article.tsx
  app/(pages)/(자유게시판)/boards/section/BestArticle.tsx
  components/content/BestBadge.tsx
  components/content/Count.tsx
  components/user/Profile.tsx
  public/svg/toggle.svg
Labels: ✨Feat, ♻️Refactor, 📦Chore

#136 fix/design: 팀 페이지 및 팀 생성하기 페이지 디자인 수정
  components/team/add_team/TeamImageInput.tsx
  components/team/with_team/MemberCard.tsx
  components/team/with_team/TeamTaskListCard.tsx
  components/team/with_team/TodoReportChartSide.tsx
Labels: 🩹Fix, 🎨Design, 🐛Bug

#141 Fix: react-dialog error 처리
  components/@common/modal/Modal.tsx
Labels: 🩹Fix, 🐛Bug

#147 Feat: 새로운 공통 모달 컴포넌트 구현
  components/@common/modal/NewModal.tsx
Labels: ✨Feat

#150 Fix: modal hydration error 수정
  components/@common/modal/NewModal.tsx
Labels: 🩹Fix, 🐛Bug

#145 Fix: 2차 QA
  components/@common/dropdown/NavigationMenu.tsx
  components/@common/dropdown/UserDropDown.tsx
  components/auth/InputField.tsx
  components/auth/login/LoginForm.tsx
  components/auth/login/ResetPasswordEmailModal.tsx
  components/auth/mypage/PasswordEditForm.tsx
  components/auth/mypage/ProfileEditInput.tsx
  components/auth/reset-password/ResetPasswordForm.tsx
  components/auth/signup/SignUpForm.tsx
Labels: 🐛Bug

#143 Fix: 1차 할 일 상세 페이지 수정
  components/taskdetail/DeleteCommentModal.tsx
  components/taskdetail/DeleteTaskModal.tsx
  components/taskdetail/EditTaskModal.tsx
  components/taskdetail/TaskComment.tsx
  components/taskdetail/TaskCommentForm.tsx
  components/taskdetail/TaskCommentList.tsx
  components/taskdetail/TaskDetail.tsx
  components/taskdetail/TaskSheet.tsx
  components/tasks/taskList/TaskCard.tsx
  queries/task.ts
Labels: ✨Feat, ♻️Refactor, 🎨Design

#148 Feat/Fix: 게시글 페이지들 기능 추가 및 버그 수정
  action/content.ts
  apis/article.ts
  apis/articleComment.ts
  app/(pages)/(자유게시판)/board/[id]/PatchAndDelete.tsx
  app/(pages)/(자유게시판)/board/[id]/PatchArticle.tsx
  app/(pages)/(자유게시판)/board/[id]/PatchComment.tsx
  app/(pages)/(자유게시판)/board/[id]/action.ts
  app/(pages)/(자유게시판)/board/[id]/page.tsx
  app/(pages)/(자유게시판)/boards/action.ts
  app/(pages)/(자유게시판)/boards/page.tsx
  app/(pages)/(자유게시판)/boards/section/Article.tsx
  app/(pages)/(자유게시판)/boards/section/BestArticle.tsx
  components/content/Count.tsx
  components/user/Profile.tsx
  dtos/Article.d.ts
Labels: ✨Feat, ♻️Refactor, 🩹Fix, 🐛Bug
