Repository Codeit-FE08-Part4-Team7/wedo, pull requests merged in 2024-11, with the labels that each got.

#155 FIx: 할 일 목록 페이지 수정 및 추가 사항
  components/calendar/Calendar.tsx
  components/calendar/CalendarStyle.css
  components/tasks/addTask/AddTaskModal.tsx
  components/tasks/addTask/SelectDate.tsx
  components/tasks/taskList/TaskCard.tsx
  components/tasks/tasksMenu/DateIcon.tsx
  components/tasks/tasksMenu/TasksDate.tsx
  dtos/TaskDtos.ts
  package-lock.json
  package.json
Labels: ✨Feat, ♻️Refactor, 🩹Fix, 📦Chore

#152 Fix: 2차 QA 추가 해결
  app/(pages)/reset-password/@auth/default.tsx
  app/(pages)/reset-password/@auth/page.tsx
  app/(pages)/reset-password/layout.tsx
  components/auth/InputField.tsx
  components/auth/login/LoginForm.tsx
  components/auth/mypage/PasswordEditForm.tsx
  components/auth/mypage/ProfileEditInput.tsx
  components/layout/AuthHeader.tsx
  lib/cookie.ts
Labels: 🩹Fix

#159 Fix: 히스토리 페이지 수정 사항
  app/(pages)/history/page.tsx
Labels: 🩹Fix

#158 Fix: NewModal의 ModalFooter 구조 변경
  components/@common/modal/NewModal.tsx
  components/team/with_team/MemberCard.tsx
  components/team/with_team/TeamDelModal.tsx
  components/team/with_team/TeamTaskListDelModal.tsx
Labels: ♻️Refactor, 🩹Fix, 🐛Bug

#161 Fix: type 오류 수정
  apis/task.ts
Labels: 🩹Fix

#162 Fix: 할 일 목록 페이지 수정
  components/tasks/taskList/TaskCard.tsx
  components/tasks/tasksMenu/TasksMenu.tsx
Labels: 🩹Fix

#164 Feat: loading.tsx 추가
  apis/action.ts
  app/(pages)/layout.tsx
  app/(pages)/loading.tsx
  app/layout.tsx
  components/@common/Loading.tsx
  components/@common/button/Submit.tsx
  components/@common/dropdown/UserDropDown.tsx
  components/auth/login/ResetPasswordEmailModal.tsx
  components/layout/AuthHeader.tsx
  components/layout/HeaderLayout.tsx
  components/ui/spinner.tsx
Labels: ✨Feat, 🩹Fix

#165 Fix: 할 일 상세 페이지 수정 사항
  app/(pages)/(team)/[teamid]/tasks/[tasklistid]/task/[taskid]/page.tsx
  components/taskdetail/TaskSheet.tsx
  components/taskdetail/tasksheet/tasksheet.tsx
Labels: ✨Feat, 🎨Design

#168 Feat: error.tsx 추가
  app/(pages)/error.tsx
Labels: ✨Feat

#166 Feat: useDeviceType 커스텀 훅 최적화 (zustand 활용)
  constants/mediaQueryBreakPoints.ts
  stores/git_tracking_file
  stores/useDeviceTypeStore.ts
Labels: ✨Feat, ♻️Refactor

#169 Refactor: isMobile값 전역 상태 이용 리팩토링
  components/@common/modal/Modal.tsx
Labels: ♻️Refactor

#171 Feat: 렌딩 페이지 작업
  app/(pages)/page.tsx
  package-lock.json
  package.json
  public/images/background_floor.png
  public/images/content_bottom.png
  public/images/content_check.png
  public/images/content_check_icon.png
  public/images/content_group.png
  public/images/content_group_icon.png
  public/images/content_invite.png
  public/images/content_invite_icon.png
  public/images/landing_logo.png
  public/images/todolist.png
Labels: ✨Feat, 🎨Design, 📦Chore

#173 Fix: 렌딩 페이지 수정 사항
  app/(pages)/page.tsx
  components/landing/LandingPage.tsx
  middleware.ts
Labels: ✨Feat, 📦Chore

#170 Feat/Fix: 게시판 페이지 기능 확장, 게시글 페이지 수정
  apis/article.ts
  app/(pages)/(자유게시판)/board/[id]/CommentForm.tsx
  app/(pages)/(자유게시판)/board/[id]/CommentList.tsx
  app/(pages)/(자유게시판)/board/[id]/PatchAndDelete.tsx
  app/(pages)/(자유게시판)/board/[id]/PatchArticle.tsx
  app/(pages)/(자유게시판)/board/[id]/action.ts
  app/(pages)/(자유게시판)/board/[id]/page.tsx
  app/(pages)/(자유게시판)/boards/action.ts
  app/(pages)/(자유게시판)/boards/page.tsx
  app/(pages)/(자유게시판)/boards/section/Article.tsx
  app/(pages)/(자유게시판)/boards/section/BestArticle.tsx
  components/board/ImagePreviewInput.tsx
  components/content/BestBadge.tsx
  components/layout/groups/GroupsResponsive.tsx
  components/layout/groups/boardsLink.tsx
  dtos/Article.d.ts
  styles/globals.css
Labels: ✨Feat, ♻️Refactor, 🩹Fix, 🎨Design, 🔧Rename

#176 Fix: 타입 에러 수정
  action/content.ts
Labels: 🩹Fix

#178 Docs: README.md 파일 추가
  README.md
Labels: 📄Docs
